### ISSUE TITLE
generate one day demand files

### ISSUE THREAD

**Issue by javieralonso** [wallarelvo/mod#3]
Generate a file for the demand of each day.
In the file name use the day of the week and week number and year: demands_D_W_Y.cvs
where
D: day of the week 1-7
W: week of the year
Y: year

**Comment by wallarelvo** [comment]
Okay, I am currently testing. There is one issue though, you do not know the number of lines in each sub file ahead of time, so the number of lines is placed at the last line of each file.

**Comment by javieralonso** [comment]
The number of requests should be written in the second line of the file.
The number of lines is that one +2

On Fri, Feb 12, 2016, 12:58 Alex Wallar <notifications@github.com> wrote:

> Okay, I am currently testing. There is one issue though, you do not know
> the number of lines in each sub file ahead of time, so the number of lines
> is placed at the last line of each file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wallarelvo/mod/issues/3#issuecomment-183430611>.
>
-- 
Dr. Javier Alonso-Mora
Computer Science and Artificial Intelligence Lab CSAIL
Massachusetts Institute of Technology MIT
Postdoctoral Associate
32 Vassar St., office 32-377, 02139 Cambridge MA, USA

**Comment by wallarelvo** [comment]
Yes but the way that files are written, you cannot put it on the second line without knowing it at the time of writing the second line

**Comment by wallarelvo** [comment]
Okay, I think I fixed it, but I had to hold things in memory for a little bit
