### ISSUE TITLE
Increase precision times files

### ISSUE THREAD

**Issue by javieralonso** [wallarelvo/mod#7]
Alex,

Could you increase the precision of the times in times.cvs to match the precision you are using for computing them?
Or, alternatively, reduce the precision of the individual edges to one decimal point, before computing all travel times.

Thanks,
Javier

**Comment by wallarelvo** [comment]
Okay, will do. You did tell me one decimal point.

--ajw

On Tue, Feb 16, 2016 at 1:45 PM javier <notifications@github.com> wrote:

> Alex,
>
> Could you increase the precision of the times in times.cvs to match the
> precision you are using for computing them?
> Or, alternatively, reduce the precision of the individual edges to one
> decimal point, before computing all travel times.
>
> Thanks,
> Javier
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wallarelvo/mod/issues/7>.
>
-- 
Alex Wallar
PhD Student
Distributed Robotics Laboratory
Computer Science and Artificial Intelligence Laboratory
Massachusetts Institute of Technology
